##
## create vagrant running docker inside
##  on circleic, use aws installed by circleci.yml
##
all: all-echo

vagrant_1.8.1_x86_64.deb:
	#wget https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb

all-echo: vagrant_1.8.1_x86_64.deb
	echo "test make commands"
